### ISSUE TITLE
0.5 - Playbook can automatically set up a Hugo website for sysadmins (no GUI).

### ISSUE THREAD

**Issue by Zarex** [maximum-ethics/linode-caddy#4]
Parameters: Domain Name of website

Steps to be automated:
1. Ensure required software is installed on the **hosting server** or install software
2. Enable Git to version website content
3. Automate creation of host server
4. Modify the Domain Control Panel on Linode to point domain to correct server 

Acceptance Criteria:
1. All of the above steps automated or documentation on steps that can't be automated

**Comment by skyfaller** [comment]
Broadly speaking, we are going to:

- Fix [the part of the role that sets up Hugo sites](https://github.com/maximum-ethics/linode-caddy/blob/arch-aur/roles/sunrise/tasks/hugo.yml), so that it sets up a website for Maximum Ethics
- using [this Hugo theme](https://git.sr.ht/~skyfaller/maxethics-hugo) and [this website-specific content / design](https://git.sr.ht/~skyfaller/maximum-ethics-website)
- First get it working in [our test environment](https://github.com/maximum-ethics/linode-caddy/blob/arch-aur/roles/sunrise/vars/local_tls.yml) and [test Caddyfile](https://github.com/maximum-ethics/linode-caddy/blob/arch-aur/roles/sunrise/templates/LocalCaddyfile.j2).
- Then, flip the switch on the domain and make it live on https://www.maximumethics.dev/ using [our production environment](https://github.com/maximum-ethics/linode-caddy/blob/arch-aur/roles/sunrise/vars/main.yml) and [production Caddyfile](https://github.com/maximum-ethics/linode-caddy/blob/arch-aur/roles/sunrise/templates/Caddyfile.j2).
