### ISSUE TITLE
Manual steps for Ansible Galaxy role

### ISSUE THREAD

**Issue by Zarex** [maximum-ethics/linode-caddy#5]
https://github.com/maximum-ethics/linode-caddy/blob/0cc58e330bc3363d605ba948822b373b0813f79d/roles/sunrise/tasks/main.yml#L1-L3
Currently we are using a manual step to install an Ansible Galaxy role to install packages from the AUR.

**Comment by skyfaller** [comment]
I'm kind of disappointed in how hard it is to automate pulling in roles from Galaxy. Is there something we're missing?

Regardless, I purged the ansible-aur Galaxy role since Caddy is now available in the official repos, albeit still [in testing](https://archlinux.org/packages/community-testing/x86_64/caddy/), so we don't need the AUR at the moment.
